name: Download Crowdin Translations
on:
  repository_dispatch:
    types: [ file-fully-translated ]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download translations and create PR
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          create_pull_request: true
          pull_request_title: 'New translations from Crowdin'
          pull_request_body: 'Completed translations have been downloaded.'
          localization_branch_name: crowdin-translations
          pull_request_base_branch_name: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
